-- ============================================================
-- Exam Topper — Study Notes Seed Data (AI Generated Batch)
-- Run AFTER supabase_schema.sql AND supabase_seed_notes.sql
-- Total: 28 new note topics across 6 subjects
-- ============================================================

INSERT INTO public.note_topics (
  id, subject, title, overview, content, key_points,
  formulas, tables_data, exam_targets, importance, estimated_read_time, is_public
)
VALUES

-- ─── Pakistan Studies (8 Notes) ───────────────────────────
('ps-note-1', 'Pakistan Studies', 'Pakistan Movement — Key Dates & Events',
 'The freedom movement from 1857 to 1947 is the most tested Pakistan Studies topic across all competitive exams.',
 'Use the mnemonic "1857-1906-1919-1930-1940-1947" to memorize key milestone years in order. Each year marks a turning point: Revolt, Muslim League, Khilafat, Allahabad Address, Lahore Resolution, Independence.',
 '["1857: War of Independence (Sepoy Mutiny) — start of British Crown rule replacing East India Company.","1906: All India Muslim League (AIML) founded in Dhaka on 30 December by Nawab Salimullah Khan.","1919: Montagu-Chelmsford Reforms; Khilafat Movement begins (1919-1924).","1930: Allahabad Address — Allama Iqbal first proposed a separate Muslim homeland in northwest India.","1940: Pakistan Resolution (Lahore Resolution) passed on 23 March at Minto Park, Lahore. Moved by A.K. Fazlul Haq.","1947: 14 August — Independence Day. Quaid-e-Azam became first Governor-General. Liaquat Ali Khan became first PM."]',
 null, null,
 '["KPPSC","ETEA","CSS","Teaching","Police","FPSC","FIA","NTS"]',
 'critical', 8, true),

('ps-note-2', 'Pakistan Studies', 'Quaid-e-Azam Muhammad Ali Jinnah — Biography & Role',
 'Understanding the political timeline of Quaid-e-Azam is essential for FPSC and CSS screening tests.',
 'Remember 1913 and 1920: He joined the Muslim League in 1913 but did not leave the Indian National Congress until 1920. His 14 Points (1929) were a direct rejection of the Nehru Report.',
 '["Born: December 25, 1876, in Wazir Mansion, Karachi.","Ambassador of Hindu-Muslim Unity: Title given by Sarojini Naidu after the 1916 Lucknow Pact.","Political Shift: Joined Muslim League in 1913, resigned from Congress in 1920 (Nagpur session).","14 Points (1929): Presented to safeguard Muslim rights against the Hindu-dominated Nehru Report.","Title of Quaid-e-Azam: Conferred by Maulana Mazharuddin Shaheed in 1938.","Governor-General: Served as the 1st GG of Pakistan from 14 Aug 1947 until his death on 11 Sep 1948."]',
 null, null,
 '["KPPSC","ETEA","CSS","Teaching","Police","FPSC","FIA","NTS"]',
 'critical', 6, true),

('ps-note-3', 'Pakistan Studies', 'Constitution of Pakistan — 1956, 1962, 1973 Comparison',
 'The differences in governmental structure across Pakistan''s three constitutions form the core of constitutional MCQs.',
 'Associate 1956 and 1973 with Parliamentary systems, and 1962 exclusively with Ayub Khan''s Presidential system. 1973 is the only one with a Bicameral (two-house) legislature.',
 '["1956 Constitution: Enforced 23 March 1956. Parliamentary, unicameral, declared Pakistan an Islamic Republic. Abrogated 1958.","1962 Constitution: Promulgated 8 June 1962 by Ayub Khan. Presidential, unicameral, introduced Basic Democracies. Abrogated 1969.","1973 Constitution: Enforced 14 August 1973 under Z.A. Bhutto. Parliamentary and bicameral (National Assembly & Senate).","Article 2A: The Objectives Resolution (1949) was made a substantive part of the 1973 Constitution via the 8th Amendment.","State Religion: All three constitutions declared Islam as the state religion, but 1973 established the Council of Islamic Ideology."]',
 null, null,
 '["KPPSC","ETEA","CSS","Teaching","Police","FPSC","FIA","NTS"]',
 'critical', 7, true),

('ps-note-4', 'Pakistan Studies', 'Geography of Pakistan — Rivers, Mountains, Provinces',
 'Border lengths, highest peaks, and major river systems are consistently tested in ETEA and NTS exams.',
 'For borders, use the acronym AIIC (Afghanistan, India, Iran, China). The Indus River is the longest (3180 km) and is referred to as the lifeline of Pakistan.',
 '["Highest Peak: K2 (Godwin-Austen) is 8,611m high, located in the Karakoram range. Nanga Parbat (8,126m) is in the Himalayas.","Longest River: Indus River (3,180 km), starting from Lake Mansarovar in Tibet and ending in the Arabian Sea.","Durand Line: 2,430 km (or 2,640 km by recent surveys) border with Afghanistan, drawn in 1893.","Radcliffe Line: Boundary demarcated between India and Pakistan in August 1947.","Coastline: Pakistan has an Arabian Sea coastline of approximately 1,046 km (mostly in Balochistan and Sindh)."]',
 null, null,
 '["KPPSC","ETEA","CSS","Teaching","Police","FPSC","FIA","NTS"]',
 'high', 7, true),

('ps-note-5', 'Pakistan Studies', 'FATA Merger into KPK — 25th Constitutional Amendment 2018',
 'The administrative integration of the tribal areas is a highly relevant contemporary topic for provincial exams.',
 'Focus on the number 25. The 25th Amendment legally erased the FATA acronym, merging its 7 agencies and 6 Frontier Regions into Khyber Pakhtunkhwa in May 2018.',
 '["Passage: The 25th Constitutional Amendment was passed by the National Assembly and Senate in May 2018.","Pre-merger Status: FATA consisted of 7 Agencies (e.g., Khyber, Waziristan) and 6 Frontier Regions governed by the President via the Governor KPK.","FCR Abolition: The draconian Frontier Crimes Regulation (FCR) of 1901 was officially repealed.","Representation: FATA''s separate seats in the National Assembly were integrated into KPK''s quota, reducing the NA total seats from 342 to 336 over time.","Provincial Assembly: First-ever provincial elections in the merged tribal districts were held in July 2019."]',
 null, null,
 '["KPPSC","ETEA","CSS","Teaching","Police","FPSC","FIA","NTS"]',
 'high', 5, true),

('ps-note-6', 'Pakistan Studies', 'Pakistan''s Nuclear Program — Timeline & Key Facts',
 'Pakistan''s journey to becoming the first Islamic nuclear power is a staple for FIA and FPSC interviews/MCQs.',
 'Remember the dates of the tests: May 28 and May 30, 1998. The title "Youm-e-Takbeer" translates to "The Day of Greatness" to commemorate this achievement.',
 '["Initiation: The nuclear program formally began in the 1970s under Prime Minister Zulfiqar Ali Bhutto.","Key Figure: Dr. Abdul Qadeer Khan (A.Q. Khan) spearheaded the uranium enrichment program at Kahuta Research Laboratories (KRL).","KANUPP: Karachi Nuclear Power Plant was Pakistan''s first commercial nuclear plant, inaugurated in 1972 with Canadian help.","Chagai-I: Pakistan conducted five simultaneous underground nuclear tests on May 28, 1998, in the Ras Koh Hills of Balochistan.","Chagai-II: A sixth test was conducted on May 30, 1998.","Global Status: Pakistan became the 7th nuclear-armed country in the world and the 1st in the Islamic world."]',
 null, null,
 '["KPPSC","ETEA","CSS","Teaching","Police","FPSC","FIA","NTS"]',
 'critical', 6, true),

('ps-note-7', 'Pakistan Studies', 'CPEC — China Pakistan Economic Corridor Details',
 'CPEC is the flagship project of China''s Belt and Road Initiative (BRI) and dominates economic current affairs.',
 'Associate CPEC with the year 2015 and Gwadar. It connects Kashgar in China’s Xinjiang province to Gwadar Port in Balochistan.',
 '["Launch: Official agreements were signed in April 2015 during Chinese President Xi Jinping''s visit to Pakistan.","Initial Value: Started with an estimated $46 billion investment, later expanding to over $62 billion.","Gwadar Port: The centerpiece deep-sea port in Balochistan, leased to China Overseas Port Holding Company (COPHC).","Three Alignments: Western, Central, and Eastern road/rail networks connecting the Arabian Sea to China.","Energy Focus: The first phase heavily prioritized resolving Pakistan''s energy crisis through coal, hydro, and solar power plants."]',
 null, null,
 '["KPPSC","ETEA","CSS","Teaching","Police","FPSC","FIA","NTS"]',
 'high', 6, true),

('ps-note-8', 'Pakistan Studies', 'Important Constitutional Amendments — 8th, 13th, 17th, 18th, 25th',
 'Constitutional amendments dictate the balance of power in Pakistan and are guaranteed questions in CSS/PMS.',
 'A simple trick for Article 58(2)(b) [President''s power to dissolve assembly]: 8th added it, 13th removed it, 17th restored it, 18th removed it permanently.',
 '["8th Amendment (1985): Passed under Zia-ul-Haq, introduced Article 58(2)(b) allowing the President to dissolve the National Assembly.","13th Amendment (1997): Passed by Nawaz Sharif, stripped the President of the power to dissolve the assembly.","17th Amendment (2003): Passed under Pervez Musharraf, restored the President''s dissolution powers.","18th Amendment (2010): Removed 58(2)(b) again, devolved federal ministries to provinces, and renamed NWFP to Khyber Pakhtunkhwa.","25th Amendment (2018): Officially merged the Federally Administered Tribal Areas (FATA) into Khyber Pakhtunkhwa."]',
 null, null,
 '["KPPSC","ETEA","CSS","Teaching","Police","FPSC","FIA","NTS"]',
 'critical', 7, true),

-- ─── General Knowledge (5 Notes) ──────────────────────────
('gk-note-5', 'General Knowledge', 'Shanghai Cooperation Organisation (SCO)',
 'SCO is a leading Eurasian political, economic, and military organization highly relevant to regional security.',
 'Pakistan and India joined together in 2017. Before 2001, it was known as the "Shanghai Five" (Russia, China, Kazakhstan, Kyrgyzstan, Tajikistan).',
 '["Formation: Officially founded on June 15, 2001, in Shanghai, China.","Headquarters: SCO Secretariat is based in Beijing, China. RATS (Regional Anti-Terrorist Structure) is based in Tashkent, Uzbekistan.","Expansion: Pakistan and India became full members in 2017 at the Astana Summit.","Newest Members: Iran joined as the 9th member in 2023, and Belarus joined as the 10th member in 2024.","Focus Areas: Regional security, combating terrorism/separatism, and economic cooperation in Central Asia."]',
 null, null,
 '["KPPSC","CSS","Teaching","Police","FPSC"]',
 'high', 5, true),

('gk-note-6', 'General Knowledge', 'Economic Cooperation Organisation (ECO)',
 'The ECO is a crucial Asian political and economic intergovernmental organization connecting Pakistan to Central Asia.',
 'ECO is the direct successor to the Regional Cooperation for Development (RCD), which was founded in 1964 by the exact same three founding nations: Pakistan, Iran, and Turkey.',
 '["Formation: Established in 1985 by Iran, Pakistan, and Turkey.","Headquarters: Located in Tehran, Iran.","Expansion: Expanded in 1992 to include 7 new members (Afghanistan, Azerbaijan, and 5 Central Asian Republics: Kazakhstan, Kyrgyzstan, Tajikistan, Turkmenistan, Uzbekistan).","Objective: Promote sustainable economic development, remove trade barriers, and integrate the region into global markets.","Key Treaty: ECO Trade Agreement (ECOTA) signed in 2003 to reduce tariffs."]',
 null, null,
 '["KPPSC","CSS","Teaching","Police","FPSC"]',
 'medium', 5, true),

('gk-note-7', 'General Knowledge', 'World Records — Largest, Smallest, Longest, Highest',
 'Static GK questions regarding global superlatives are guaranteed in one-paper MCQs (FIA, NTS, KPPSC).',
 'Always distinguish between deepest and largest. The Pacific is both the deepest and largest ocean. The Nile is the longest river, but the Amazon has the largest water volume.',
 '["The Vatican is technically a sovereign city-state and holds the record for both the smallest area and smallest population.","Mount Everest''s height is officially recognized as 8,848.86 meters after a joint Nepal-China remeasurement in 2020.","The Caspian Sea is technically the world''s largest inland body of water, making it a lake despite its name."]',
 null,
 '[{"headers":["Category","Record Holder","Detail"],"rows":[["Largest country","Russia","By total land area"],["Smallest country","Vatican","By land area and population"],["Longest river","Nile","Located in Africa, approx. 6,650 km"],["Highest mountain","Everest","8,848.86 meters, Himalayas"],["Deepest ocean","Pacific","Mariana Trench is the deepest point"],["Largest ocean","Pacific","Covers approx. 30% of Earth''s surface"],["Longest wall","Great Wall of China","Over 21,000 km in length"],["Most populated country","India","Surpassed China in 2023"],["Largest desert","Sahara","Largest hot desert, located in Africa"],["Largest lake","Caspian Sea","Largest enclosed inland body of water"]]}]',
 '["KPPSC","CSS","Teaching","Police","FPSC"]',
 'critical', 6, true),

('gk-note-8', 'General Knowledge', 'Nobel Prize — Categories, History & Recent Winners',
 'The Nobel Prize is the most prestigious international award and a recurring GK topic in FPSC and CSS.',
 'The Economics prize was NOT in Alfred Nobel''s original will; it was added later in 1968. Peace prizes are awarded in Norway, while all others are awarded in Sweden.',
 '["Origin: Established by the 1895 will of Alfred Nobel, a Swedish chemist who invented dynamite. First awarded in 1901.","Categories: 6 categories (Physics, Chemistry, Medicine, Literature, Peace, and Economic Sciences).","Locations: The Peace Prize is awarded in Oslo, Norway. All other prizes are awarded in Stockholm, Sweden.","Pakistani Laureates: Dr. Abdus Salam (Physics, 1979) and Malala Yousafzai (Peace, 2014 - youngest ever recipient).","Nobel Rule: Cannot be awarded posthumously (unless the laureate dies after announcement) and shared by a maximum of three individuals."]',
 null, null,
 '["KPPSC","CSS","Teaching","Police","FPSC"]',
 'high', 6, true),

('gk-note-9', 'General Knowledge', 'G7 vs G20 — Members, Purpose, Key Summits',
 'Differentiating global economic alliances is vital for current affairs and international relations screening.',
 'The G7 is exclusively advanced, wealthy democracies. The G20 includes the G7 plus major developing economies like India, Brazil, and China.',
 '["G7 Formation: Created in 1975. Members: USA, UK, France, Germany, Italy, Canada, Japan. (Russia was expelled in 2014, ending the G8).","G7 Purpose: Informal bloc of advanced democracies discussing global economic governance and security.","G20 Formation: Established in 1999 in response to Asian financial crises. Represents 80% of global GDP.","G20 Membership: 19 sovereign nations plus the EU and the African Union (added in 2023).","Recent Summits: G20 Summit 2023 was hosted by India (New Delhi); 2024 hosted by Brazil (Rio de Janeiro)."]',
 null, null,
 '["KPPSC","CSS","Teaching","Police","FPSC"]',
 'medium', 5, true),

-- ─── English (4 Notes) ────────────────────────────────────
('eng-note-3', 'English', 'Active and Passive Voice — Complete Rules',
 'Voice conversion is heavily tested in ETEA and KPPSC. The core rule is that the tense NEVER changes, only the verb form.',
 'To convert passive voice quickly, look for the "Be + V3 (Past Participle)" structure. If the original sentence is present continuous, the passive MUST contain "being".',
 '["Rule 1: Subject and Object swap places. The preposition ''by'' is generally added before the new object.","Rule 2: The main verb is ALWAYS converted to its 3rd form (Past Participle).","Rule 3 (Continuous Tense): Add ''being''. Example: He is writing a letter -> A letter is being written by him.","Rule 4 (Perfect Tense): Add ''been''. Example: She has finished work -> Work has been finished by her.","Rule 5 (Modals): Add ''be'' after the modal. Example: You must do this -> This must be done by you.","Rule 6 (Imperative): Use ''Let''. Example: Open the door -> Let the door be opened."]',
 null, null,
 '["KPPSC","ETEA","CSS","Teaching","Police","FPSC","FIA"]',
 'critical', 7, true),

('eng-note-4', 'English', 'Direct and Indirect Speech — Reporting Rules',
 'Narration questions often trap students on pronoun changes and time-word backshifting. Mastering SON rule is key.',
 'Use the SON rule for pronouns: Subjects change according to 1st person, Objects to 2nd person, and No Change for 3rd person. Always step tenses backward into the past.',
 '["Tense Change: If reporting verb is in the past, Present Simple -> Past Simple; Present Continuous -> Past Continuous.","Past Perfect Exception: Past Perfect and Past Perfect Continuous do NOT change in indirect speech.","Time Words: ''Today'' becomes ''that day'', ''tomorrow'' becomes ''the next day'', ''yesterday'' becomes ''the previous day''.","Place Words: ''Here'' becomes ''there'', ''this'' becomes ''that'', ''these'' becomes ''those''.","Interrogative Sentences: Remove question mark, use ''if'' or ''whether'' for yes/no questions, and change word order to subject-verb."]',
 null, null,
 '["KPPSC","ETEA","CSS","Teaching","Police","FPSC","FIA"]',
 'critical', 7, true),

('eng-note-5', 'English', 'Common One-Word Substitutions for Exams',
 'One-word substitution tests your vocabulary precision and saves reading time during the English vocabulary sections.',
 'Learn root words. "Philo" means love (Philanthropist = lover of mankind), while "Misan" means hate (Misanthrope = hater of mankind). "Omni" means all.',
 '["A person who doesn''t believe in God: Atheist.","One who looks at the bright side of things: Optimist. (Dark side = Pessimist)","A person present everywhere: Omnipresent. (All-powerful = Omnipotent, All-knowing = Omniscient)","A person who hates mankind: Misanthrope.","A person who is indifferent to pleasure or pain: Stoic.","Something that cannot be avoided: Inevitable.","A life history written by oneself: Autobiography. (Written by someone else = Biography)"]',
 null, null,
 '["KPPSC","ETEA","CSS","Teaching","Police","FPSC","FIA"]',
 'high', 5, true),

('eng-note-6', 'English', 'High-Frequency CSS-Level Vocabulary List',
 'FPSC and CSS exams use advanced academic vocabulary in synonym, antonym, and sentence completion questions.',
 'Do not just memorize the translation; understand the context. For instance, "mitigate" is used for pain or disaster, not physical size.',
 '["Mastering these 12 words covers over 40% of the recurring difficult synonyms in FPSC past papers.","Focus on adjectives and verbs, as they constitute the majority of sentence completion blanks.","Use root word connections (e.g., ''ephemera'' means short-lived insects, linking to Ephemeral)."]',
 null,
 '[{"headers":["Word","Meaning","Category"],"rows":[["Abate","To lessen or reduce in intensity","Verb"],["Capricious","Given to sudden, unaccountable changes of mood","Adjective"],["Enigma","A person or thing that is mysterious or difficult to understand","Noun"],["Ephemeral","Lasting for a very short time","Adjective"],["Fastidious","Very attentive to and concerned about accuracy and detail","Adjective"],["Garrulous","Excessively talkative, especially on trivial matters","Adjective"],["Lethargic","Sluggish and apathetic; lacking energy","Adjective"],["Mitigate","Make less severe, serious, or painful","Verb"],["Obscure","Not discovered or known about; uncertain","Adjective"],["Pragmatic","Dealing with things sensibly and realistically","Adjective"],["Reticent","Not revealing one''s thoughts or feelings readily","Adjective"],["Sycophant","A person who acts obsequiously toward someone important to gain advantage","Noun"]]}]',
 '["KPPSC","ETEA","CSS","Teaching","Police","FPSC","FIA"]',
 'high', 8, true),

-- ─── Mathematics (3 Notes) ────────────────────────────────
('math-note-3', 'Mathematics', 'Time, Speed & Distance — Formula Sheet',
 'Essential for NTS and ETEA math portions. Train problems and relative speed are the most repeated sub-types.',
 'The golden conversion rule: To convert km/h to m/s, multiply by (5/18). To convert m/s to km/h, multiply by (18/5).',
 '["Basic Relationship: Distance equals Speed multiplied by Time (D = S * T).","Average Speed: For equal distances traveled at speeds x and y, Average Speed = 2xy / (x + y). NOT just (x+y)/2.","Relative Speed (Same Direction): Subtract the speeds (S1 - S2). E.g., Police chasing a thief.","Relative Speed (Opposite Direction): Add the speeds (S1 + S2). E.g., Two trains crossing each other.","Train Crossing Pole: Distance = Length of the train.","Train Crossing Platform: Distance = Length of train + Length of platform."]',
 '[{"name":"Distance Formula","equation":"D = S * T","application":"Core formula for all kinematics"},{"name":"km/h to m/s","equation":"Speed * (5/18)","application":"Convert large scale speed to seconds"},{"name":"Average Speed (Equal Dist)","equation":"2xy / (x + y)","application":"Round trips at different speeds"}]',
 null,
 '["ETEA","Teaching","Computer Operator","Police","FPSC","NTS"]',
 'critical', 6, true),

('math-note-4', 'Mathematics', 'LCM, HCF & Number System Tricks',
 'LCM (Least Common Multiple) and HCF (Highest Common Factor) logic questions appear in almost every screening test.',
 'Always remember the master property: For any two numbers, Product of the numbers = LCM × HCF. If three values are given, you can instantly find the fourth.',
 '["HCF (Highest Common Factor): The largest number that divides two or more numbers without a remainder.","LCM (Least Common Multiple): The smallest number that is a multiple of two or more numbers.","Co-Primes: Two numbers are co-prime if their HCF is 1. (e.g., 8 and 15).","Fraction HCF: HCF of Numerators / LCM of Denominators.","Fraction LCM: LCM of Numerators / HCF of Denominators.","Bell Ringing Problem: If 3 bells ring at intervals of x, y, z mins, they will ring together again after LCM(x, y, z) mins."]',
 '[{"name":"Product Rule","equation":"A * B = LCM * HCF","application":"Finding missing LCM/HCF or one of the numbers"},{"name":"HCF of Fractions","equation":"HCF(num) / LCM(den)","application":"Finding HCF of fractional data"}]',
 null,
 '["ETEA","Teaching","Computer Operator","Police","FPSC","NTS"]',
 'high', 5, true),

('math-note-5', 'Mathematics', 'Profit, Loss & Discount Calculations',
 'Commercial math forms the backbone of basic arithmetic tests. It assesses practical percentage applications.',
 'Profit and Loss are ALWAYS calculated on the Cost Price (CP), never the Selling Price. Discount is ALWAYS calculated on the Marked Price (MP).',
 '["Cost Price (CP): The price at which goods are bought.","Selling Price (SP): The price at which goods are sold.","Profit: Occurs when SP > CP. Profit = SP - CP.","Loss: Occurs when CP > SP. Loss = CP - SP.","Discount: A reduction given on the Marked Price (MP). SP = MP - Discount.","Dishonest Dealer: If he sells at CP but uses false weight, Profit% = (Error / True Value - Error) * 100."]',
 '[{"name":"Profit Percentage","equation":"(Profit / CP) * 100","application":"Find profit relative to investment"},{"name":"Loss Percentage","equation":"(Loss / CP) * 100","application":"Find loss relative to investment"},{"name":"SP from Discount","equation":"MP * ((100 - Discount%) / 100)","application":"Calculate final checkout price"}]',
 null,
 '["ETEA","Teaching","Computer Operator","Police","FPSC","NTS"]',
 'high', 6, true),

-- ─── Computer Science (3 Notes) ───────────────────────────
('cs-note-2', 'Computer Science', 'MS Office Keyboard Shortcuts — Word, Excel, PowerPoint',
 'Keyboard shortcuts are a staple in Computer Operator and clerical exams (FPSC, KPPSC, NTS).',
 'In MS Word, Ctrl+E is for Center Alignment (not Ctrl+C, which is Copy). In PowerPoint, F5 starts the presentation from the beginning, while Shift+F5 starts from the current slide.',
 '["Most shortcut MCQs test exceptions (like Ctrl+K for Hyperlink, not H) or application-specific keys.","Excel shortcuts often involve Shift and Alt modifiers for row/column operations.","Memorize navigation keys: Ctrl+Home takes you to the absolute start of a document."]',
 null,
 '[{"headers":["Shortcut","Application","Function"],"rows":[["Ctrl + C","General","Copy selected text/item"],["Ctrl + V","General","Paste copied text/item"],["Ctrl + Z","General","Undo last action"],["Ctrl + Y","General","Redo last action"],["Ctrl + S","General","Save document"],["Ctrl + F","General","Open Find/Search box"],["Ctrl + P","General","Print document"],["Ctrl + K","Word / Excel","Insert Hyperlink"],["Ctrl + E","Word","Center align text"],["Ctrl + J","Word","Justify align text"],["Ctrl + Home","General","Move to the beginning of document"],["Ctrl + End","General","Move to the end of document"],["F5","PowerPoint","Start slide show from beginning"],["Shift + F5","PowerPoint","Start slide show from current slide"],["F2","Excel","Edit the active cell"]]}]',
 '["ETEA","Computer Operator","KPPSC","FPSC","NTS"]',
 'critical', 6, true),

('cs-note-3', 'Computer Science', 'Database Management — Keys, Normalization & SQL Basics',
 'Core concepts of RDBMS, keys, and normalization forms are heavily tested in IT and Computer Science specific posts.',
 'Primary Keys must be unique and NOT NULL. A Foreign Key in one table points to a Primary Key in another table to establish a relationship.',
 '["Primary Key: Uniquely identifies each record in a table.","Foreign Key: A field that links to the primary key of another table.","1st Normal Form (1NF): Eliminates repeating groups; ensures atomic (indivisible) values.","2nd Normal Form (2NF): Must be in 1NF and have no partial dependencies.","3rd Normal Form (3NF): Must be in 2NF and have no transitive dependencies.","SQL DML: Data Manipulation Language includes SELECT, INSERT, UPDATE, DELETE.","SQL DDL: Data Definition Language includes CREATE, ALTER, DROP."]',
 null, null,
 '["ETEA","Computer Operator","KPPSC","FPSC","NTS"]',
 'high', 6, true),

('cs-note-4', 'Computer Science', 'Cybersecurity Fundamentals — Types of Attacks & Defenses',
 'With growing digital threats, basic network security terms are frequently included in general IT screening tests.',
 'Phishing relies on human deception (fake emails), whereas malware and DDoS are technical attacks. DDoS aims to crash a server by overwhelming it with fake traffic.',
 '["Phishing: Fraudulent attempts to obtain sensitive info by disguising as a trustworthy entity via email.","Malware: Malicious software including viruses, worms, trojans, and ransomware.","Ransomware: Encrypts user data and demands payment for the decryption key.","DDoS (Distributed Denial of Service): Overwhelming a target server or network with a flood of internet traffic.","SQL Injection: Inserting malicious SQL code into input fields to manipulate backend databases.","Firewall: A network security system that monitors and controls incoming/outgoing traffic based on rules."]',
 null, null,
 '["ETEA","Computer Operator","KPPSC","FPSC","NTS"]',
 'medium', 5, true),

-- ─── Islamiat (5 Notes) ───────────────────────────────────
('isl-note-1', 'Islamiat', 'Holy Quran — Key Facts & Statistics',
 'Structural facts about the Holy Quran are standard in the compulsory Islamiat sections of all competitive exams.',
 'Surah Al-Tauba is the only Surah that does not begin with Bismillah. Surah Al-Naml contains Bismillah twice.',
 '["The Holy Quran was revealed over a period of approximately 23 years.","Makki Surahs generally focus on faith, monotheism, and the hereafter. Madni Surahs focus on laws, society, and statecraft.","The longest Surah is Al-Baqarah, and the shortest is Al-Kauthar.","The first revelation occurred in the Cave of Hira (Surah Al-Alaq, verses 1-5)."]',
 null,
 '[{"headers":["Category","Detail"],"rows":[["Total Surahs","114 (86 Makki, 28 Madni)"],["Total Paras/Juz","30"],["Total Ayats","Approx. 6236 (traditional count)"],["First Surah","Surah Al-Fatiha (in compilation)"],["Last Surah","Surah An-Nas"],["Longest Surah","Surah Al-Baqarah"],["Shortest Surah","Surah Al-Kauthar"],["First Revelation","Surah Al-Alaq (Cave of Hira, 610 CE)"],["Last Revelation","Surah Al-Maidah, Verse 3 (or Surah Al-Nasr)"]]}]',
 '["KPPSC","ETEA","CSS","Teaching","Police","FPSC","NTS"]',
 'critical', 6, true),

('isl-note-2', 'Islamiat', 'Life of Prophet Muhammad (PBUH) — Key Dates & Events',
 'Seerah (Life of the Prophet PBUH) forms the foundational basis of the Islamiat curriculum for FPSC and CSS.',
 'The year 622 CE is critical: it marks the Hijrah (migration) from Makkah to Madinah, which initiates the Islamic Hijri calendar.',
 '["Birth: Born in Makkah in the Year of the Elephant (approx. 570 CE).","First Revelation: At the age of 40 (approx. 610 CE) in the Cave of Hira.","Boycott of Banu Hashim: A harsh social and economic boycott lasting 3 years in Shib Abi Talib.","Year of Sorrow (Aam-ul-Huzn): Death of his wife Hazrat Khadija (RA) and uncle Abu Talib.","Hijrah (622 CE): Migration to Madinah, marking the beginning of the Islamic calendar.","Charter of Madinah: The first written constitution creating a pluralistic state in Madinah.","Demise: Passed away in 11 AH (632 CE) and is buried in Masjid-e-Nabawi, Madinah."]',
 null, null,
 '["KPPSC","ETEA","CSS","Teaching","Police","FPSC","NTS"]',
 'critical', 8, true),

('isl-note-3', 'Islamiat', 'Khulafa-e-Rashideen — The Four Rightly Guided Caliphs',
 'The Rashidun Caliphate period (632–661 CE) includes key institutional, administrative, and military milestones.',
 'Hazrat Umar (RA) established the police force, postal system, and the Hijri calendar. Hazrat Uthman (RA) unified the Quranic recitation.',
 '["Hazrat Abu Bakr (RA): Suppressed the Ridda (apostasy) wars and initiated the compilation of the Quran.","Hazrat Umar (RA): Conquered Jerusalem, Egypt, and Persia. Established administrative departments (Diwan).","Hazrat Uthman (RA): Expanded the navy and standardized the Holy Quran into a single unified dialect.","Hazrat Ali (RA): Moved the capital from Madinah to Kufa; his era was marked by internal civil strife (Battles of Jamal and Siffin)."]',
 null,
 '[{"headers":["Caliph","Period","Key Achievement","Martyrdom"],"rows":[["Hazrat Abu Bakr (RA)","632 - 634 CE","Suppressed rebellions, compiled Quran","Natural death"],["Hazrat Umar (RA)","634 - 644 CE","Vast expansions, established Diwan/Police","Assassinated by Abu Lu''lu''a"],["Hazrat Uthman (RA)","644 - 656 CE","Standardized Quran dialect, naval forces","Assassinated by rebels"],["Hazrat Ali (RA)","656 - 661 CE","Shifted capital to Kufa, scholarly wisdom","Assassinated by Ibn Muljam"]]}]',
 '["KPPSC","ETEA","CSS","Teaching","Police","FPSC","NTS"]',
 'critical', 7, true),

('isl-note-4', 'Islamiat', 'Five Pillars of Islam — Complete Details',
 'Fundamental obligations in Islam, including their chronological obligation years, are universally tested.',
 'Memorize the Hijri years of obligation: Salah, Sawm (Fasting), and Zakat were all institutionalized in 2 AH. Hajj became obligatory later in 9 AH.',
 '["Shahadah (Faith): The declaration of belief in the Oneness of Allah and the prophethood of Muhammad (PBUH).","Salah (Prayer): Five daily prayers became obligatory during the night of Mi''raj. Institutionalized in 2 AH.","Zakat (Charity): Obligatory almsgiving of 2.5% on accumulated wealth over a lunar year. Made mandatory in 2 AH.","Sawm (Fasting): Fasting during the month of Ramadan. Made obligatory in 2 AH.","Hajj (Pilgrimage): Mandatory once in a lifetime for those physically and financially able. Made obligatory in 9 AH. Prophet (PBUH) performed only 1 Hajj in 10 AH."]',
 null, null,
 '["KPPSC","ETEA","CSS","Teaching","Police","FPSC","NTS"]',
 'high', 6, true),

('isl-note-5', 'Islamiat', 'Major Battles in Islamic History',
 'Ghazwat (battles in which the Prophet PBUH participated) are frequently asked in MCQs regarding years, causes, and outcomes.',
 'Associate Badr with 2 AH, Uhud with 3 AH, and Khandaq (Trench) with 5 AH. The Conquest of Makkah took place in 8 AH without bloodshed.',
 '["Battle of Badr (2 AH): First major battle. 313 Muslims defeated a heavily armed Quraish army of 1,000. Abu Jahl was killed.","Battle of Uhud (3 AH): Quraish sought revenge. Muslims suffered losses due to archers leaving their post. Hazrat Hamza (RA) was martyred.","Battle of Khandaq/Trench (5 AH): Muslims dug a trench around Madinah (suggested by Salman Farsi RA) to thwart a siege by an alliance of enemies.","Treaty of Hudaybiyyah (6 AH): A pivotal 10-year peace treaty signed with the Quraish.","Battle of Khaybar (7 AH): Fought against Jewish tribes. Hazrat Ali (RA) showed immense bravery at the Fort of Qamus.","Conquest of Makkah (8 AH): Peaceful takeover of Makkah after the Quraish broke the Treaty of Hudaybiyyah."]',
 null, null,
 '["KPPSC","ETEA","CSS","Teaching","Police","FPSC","NTS"]',
 'critical', 8, true)

ON CONFLICT (id) DO UPDATE SET
  subject              = EXCLUDED.subject,
  title                = EXCLUDED.title,
  overview             = EXCLUDED.overview,
  content              = EXCLUDED.content,
  key_points           = EXCLUDED.key_points,
  formulas             = EXCLUDED.formulas,
  tables_data          = EXCLUDED.tables_data,
  exam_targets         = EXCLUDED.exam_targets,
  importance           = EXCLUDED.importance,
  estimated_read_time  = EXCLUDED.estimated_read_time,
  is_public            = EXCLUDED.is_public;