-- ============================================================
-- Smart Prep MCQs — Vocabulary Words Seeding
-- Run in the Supabase SQL Editor after running supabase_schema.sql
-- ============================================================

INSERT INTO public.vocab_words (id, word, meaning, urdu_meaning, synonyms, antonyms, example, category, is_public)
VALUES
  ('vocab-1', 'Pragmatic',
   'Dealing with things sensibly and realistically in a way that is based on practical rather than theoretical considerations.',
   'عملی / حقیقت پسندانہ (Amli / Haqeeqat-pasandana)',
   '["practical","matter-of-fact","realistic","utilitarian"]',
   '["idealistic","unrealistic","impractical","visionary"]',
   'The tehsildar took a pragmatic approach to resolve the boundary dispute between the two groups, settling it with mutual concessions.',
   'General Vocabulary', true),

  ('vocab-2', 'Anachronism',
   'A thing belonging or appropriate to a period other than that in which it exists, especially a thing that is conspicuously old-fashioned.',
   'عہدی غلطی / بے وقت چیز (Zamana ghalati / Be-waqt chiz)',
   '["misplacement","prochronism","parachronism","solecism"]',
   '["contemporary","modernity","synchronism"]',
   'Using a slide rule for calculations in a computer operator exam is a total anachronism in this modern era.',
   'CSS Vocab', true),

  ('vocab-3', 'Ameliorate',
   'Make (something bad or unsatisfactory) better.',
   'بہتر بنانا / سدھارنا (Behtar banana / Sudharna)',
   '["improve","better","enhance","upgrade","ease"]',
   '["worsen","deteriorate","exacerbate","damage"]',
   'The new administration took serious initiatives to ameliorate the standard of kppsc selection standards.',
   'CSS Vocab', true),

  ('vocab-4', 'Obfuscate',
   'Render obscure, unclear, or unintelligible.',
   'گول مول کرنا / دھندلا دینا (Gool mool karna / Dhundla dena)',
   '["confound","muddle","blur","complicate","darken"]',
   '["clarify","lucidate","explain","simplify"]',
   'The developer''s explanation only served to obfuscate the real issues inside the network protocol.',
   'Computer Science Vocab', true),

  ('vocab-5', 'Capricious',
   'Given to sudden and unaccountable changes of mood or behavior.',
   'من موجی / غیر مستقل مزاج (Man-mauji / Ghayr-mustaqil)',
   '["fickle","inconstant","volatile","arbitrary","unpredictable"]',
   '["stable","consistent","predictable","constant"]',
   'Due to the capricious weather in the Karakoram range, climbers were advised to freeze ascending plans immediately.',
   'General Vocabulary', true),

  ('vocab-6', 'Fastidious',
   'Very attentive to and concerned about accuracy and detail.',
   'نکتہ چیں / باریک بین / شکی مزاج (Bareek-been / Nuktah-cheen)',
   '["scrupulous","meticulous","exacting","finicky","demanding"]',
   '["lax","careless","easygoing","indifferent"]',
   'He was fastidious about grammar rules in his CSS descriptive essays, securing top coordinates in English.',
   'CSS Vocab', true),

  ('vocab-7', 'Ephemeral',
   'Lasting for a very short time.',
   'عارضی / فانی / عجلت پسند (Aari-zee / Fani / Chand roza)',
   '["transient","fleeting","momental","evanescent","passing"]',
   '["everlasting","perpetual","eternal","permanent"]',
   'The pleasure of cramming random GK papers is ephemeral; only daily pragmatic prep secures a regular seat.',
   'General Vocabulary', true),

  ('vocab-8', 'Abstain',
   'Formally decline to vote either for or against a proposal, or restrain oneself from doing something.',
   'پریز کرنا / دور رہنا / باز رہنا (Parhez karna / Baaz rehna)',
   '["refrain","desist","forgo","avoid","shun"]',
   '["indulge","partake","participate","embrace"]',
   'Candidates should abstain from bringing any electronic calculators into the ETEA inspection facilities.',
   'General Vocabulary', true),

  ('acronym-1', 'CPEC',
   'China-Pakistan Economic Corridor - A multi-billion dollar bilateral infrastructure, energy, and trade route development initiative linking Gwadar port to Xinjiang, China.',
   'پاک چین اقتصادی راہداری (Pak-China Iqtisadi Rahdari)',
   '["economic corridor","strategic trade link","bilateral gateway","regional connectivity"]',
   '["isolationism","trade barrier"]',
   'CPEC remains a frequently tested topic in current affairs essays for both KPPSC and CSS examinations.',
   'Exam Acronym', true),

  ('acronym-2', 'FATF',
   'Financial Action Task Force - An intergovernmental organisation founded to develop policies to combat money laundering and terrorism financing.',
   'فنانشل ایکشن ٹاسک فورس (Financial Action Task Force)',
   '["global financial monitor","anti-money laundering body","financial watchdog"]',
   '[]',
   'Questions about Pakistan''s listing and progress in FATF are regular features in ETEA and FIA papers.',
   'Exam Acronym', true),

  ('acronym-3', 'KPPSC',
   'Khyber Pakhtunkhwa Public Service Commission - The principal provincial agency responsible for conducting recruitment examinations for civil service positions.',
   'خیبر پختونخوا پبلک سروس کمیشن (Khyber Pakhtunkhwa Public Service Commission)',
   '["provincial commission","selection agency","provincial recruitment desk"]',
   '[]',
   'KPPSC candidates master descriptive essays and negative marking guidelines to secure gazetted appointments.',
   'Exam Acronym', true),

  ('acronym-4', 'ETEA',
   'Educational Testing and Evaluation Agency - An autonomous testing authority in Khyber Pakhtunkhwa established to ensure transparency in academic admissions and public jobs.',
   'ایجوکیشنل ٹیسٹنگ اینڈ ایویلیوایشن ایجنسی (Educational Testing and Evaluation Agency)',
   '["provincial testing service","evaluation agency","testing authority"]',
   '[]',
   'Practicing repeated past MCQs is the golden secret to cracking ETEA competitive screening tests.',
   'Exam Acronym', true),

  ('acronym-5', 'CSS',
   'Central Superior Services - The highly competitive federal elite civil service system of Pakistan, recruiting top personnel through intensive annual examinations.',
   'سینٹرل سپیریئر سروسز / وفاقی سول سروس (Central Superior Services)',
   '["federal bureaucracy","elite civil service","bureaucratic screening"]',
   '[]',
   'Securing a top rank in the CSS requires outstanding command over English composition and analytical current affairs.',
   'Exam Acronym', true),

  ('vocab-9', 'Aberration',
   'A departure from what is normal, usual, or expected, typically one that is unwelcome.',
   'انحراف / بے راہ روی (Inhiraf / Be-rah-ravi)',
   '["anomaly","deviation","divergence","abnormality"]',
   '["normality","conformity","regularity","standard"]',
   'The leakage of the screening test paper was described as a temporary aberration in ETEA''s history.',
   'CSS Vocab', true),

  ('vocab-10', 'Abnegation',
   'The solemn rejection or renunciation of a belief, doctrine, or self-interest.',
   'دستبرداری / انکارِ ذات (Dastbardari / Inkar-e-zaat)',
   '["renunciation","self-denial","abjuration","surrender"]',
   '["indulgence","assertion","acceptance","retention"]',
   'His sudden abnegation of the prestigious CSS seat surprised his family and peers.',
   'CSS Vocab', true),

  ('vocab-11', 'Alacrity',
   'Brisk and cheerful readiness, eagerness, or willingness.',
   'تیزی / شوق و مستعدی (Tezi / Shauq-o-mustaidi)',
   '["eagerness","enthusiasm","promptness","readiness"]',
   '["apathy","sluggishness","indifference","lethargy"]',
   'The newly selected police sub-inspectors accepted their field assignments with great alacrity.',
   'KPPSC Vocab', true),

  ('vocab-12', 'Anomalous',
   'Deviating from what is standard, normal, or expected.',
   'خلاف معمول / بے قاعدہ (Khilaf-e-mamool / Be-qaida)',
   '["atypical","irregular","unusual","peculiar"]',
   '["normal","typical","regular","standard"]',
   'The computer operator flagged an anomalous spike in system login attempts during the late hours.',
   'General Vocabulary', true),

  ('vocab-13', 'Assiduous',
   'Showing great care, attention, and persistent effort.',
   'محنتی / مستقل مزاج (Mehnat-kash / Mustaqil-mizaj)',
   '["diligent","meticulous","industrious","painstaking"]',
   '["lazy","negligent","careless","indolent"]',
   'Only an assiduous student can cover the massive syllabus of CSS current affairs in six months.',
   'CSS Vocab', true),

  ('vocab-14', 'Bellicose',
   'Demonstrating aggression and willingness to fight.',
   'جنگجو / لڑاکا (Jang-joo / Laraka)',
   '["hostile","belligerent","pugnacious","combative"]',
   '["peaceable","amicable","pacific","dovish"]',
   'The bellicose rhetoric between the political rivals escalated just days before the provincial elections.',
   'FPSC Vocab', true),

  ('vocab-15', 'Cacophony',
   'A harsh, discordant mixture of sounds.',
   'شور و غوغا / بے سری آواز (Shor-o-ghogha / Besuri awaz)',
   '["din","racket","discordance","harshness"]',
   '["harmony","euphony","silence","melody"]',
   'The cacophony in the public testing hall made it difficult for candidates to focus on math problems.',
   'General Vocabulary', true),

  ('vocab-16', 'Clemency',
   'Mercy, leniency, or mildness in executing judgment.',
   'رحم دلی / نرمی (Rehm-dili / Narmi)',
   '["leniency","mercy","mildness","compassion"]',
   '["severity","ruthlessness","cruelty","strictness"]',
   'The governor rejected the appeal for clemency filed by the convict under the local security laws.',
   'FPSC Vocab', true),

  ('vocab-17', 'Cogent',
   'Clear, logical, and convincing of an argument or case.',
   'معقول / مدلل / اثر انگیز (Maqool / Mudallal / Asar-angeez)',
   '["compelling","convincing","logical","persuasive"]',
   '["weak","unconvincing","invalid","illogical"]',
   'She presented a cogent defense of the economic reforms in her KPPSC interview.',
   'CSS Vocab', true),

  ('vocab-18', 'Conundrum',
   'A confusing and difficult problem or question.',
   'معمہ / پہیلی (Muamma / Paheli)',
   '["riddle","puzzle","dilemma","quandary"]',
   '["solution","resolution","clarity"]',
   'Managing high inflation while maintaining growth is a chronic conundrum for Pakistani policy makers.',
   'General Vocabulary', true),

  ('vocab-19', 'Dearth',
   'A scarcity or lack of something.',
   'کمی / قحط / قلت (Kami / Qahat / Qillat)',
   '["scarcity","shortage","deficiency","paucity"]',
   '["abundance","surfeit","plenty","excess"]',
   'A dearth of qualified IT professionals in public departments has delayed the digitization project.',
   'FPSC Vocab', true),

  ('vocab-20', 'Decorum',
   'Behavior in keeping with good taste and propriety.',
   'شائستگی / آداب و وقار (Shaistagi / Aadab-o-waqar)',
   '["propriety","decency","politeness","correctness"]',
   '["impropriety","indecency","rudeness","solecism"]',
   'Candidates are strictly instructed to maintain decorum and peace inside the exam centers.',
   'General Vocabulary', true),

  ('vocab-21', 'Ebullient',
   'Cheerful, full of energy, and exuberant.',
   'جوشیلہ / پرجوش (Josheela / Pur-josh)',
   '["exuberant","buoyant","joyful","animated"]',
   '["depressed","apathetic","gloomy","lethargic"]',
   'The aspirants were in an ebullient mood after seeing that the GK paper was relatively straightforward.',
   'General Vocabulary', true),

  ('vocab-22', 'Enervate',
   'Make (someone) feel drained of energy or vitality; weaken.',
   'کمزور کرنا / نڈھال کرنا (Kamzor karna / Nidhal karna)',
   '["exhaust","fatigue","weaken","devitalize"]',
   '["energize","invigorate","strengthen","refresh"]',
   'The hot and humid weather during the three-hour ETEA exam threatened to enervate the applicants.',
   'CSS Vocab', true),

  ('vocab-23', 'Equivocal',
   'Open to more than one interpretation; ambiguous or uncertain.',
   'گول مول / مبہم (Gool mool / Mubham)',
   '["ambiguous","vague","evasive","indeterminate"]',
   '["clear","unequivocal","plain","explicit"]',
   'The commission gave an equivocal response regarding the final date of the screening tests.',
   'KPPSC Vocab', true),

  ('vocab-24', 'Esoteric',
   'Intended for or likely to be understood by only a small number of people with specialized knowledge.',
   'پوشیدہ / رمزآمیز / خفیہ (Poshida / Ramz-ameez)',
   '["obscure","mysterious","arcane","recondite"]',
   '["public","commonplace","familiar","manifest"]',
   'The paper included esoteric questions about ancient regional treaties that few students had prepared.',
   'CSS Vocab', true),

  ('vocab-25', 'Exculpate',
   'Show or declare that someone is not guilty of wrongdoing.',
   'بری کرنا / بے گناہ ٹھہرانا (Bari karna / Begunah thehrana)',
   '["exonerate","absolve","acquit","vindicate"]',
   '["incriminate","convict","condemn","blame"]',
   'The forensic report served to exculpate the junior clerk accused of administrative malpractice.',
   'FPSC Vocab', true),

  ('vocab-26', 'Garrulous',
   'Excessively talkative, especially on trivial matters.',
   'باتونی / فضول گو (Batuni / Fuzool-go)',
   '["talkative","loquacious","chatty","verbose"]',
   '["taciturn","quiet","reticent","silent"]',
   'The invigilator warned the garrulous candidates that talking during the exam would lead to paper cancellation.',
   'CSS Vocab', true),

  ('vocab-27', 'Harangue',
   'A lengthy and aggressive speech or lecture.',
   'جوشیلہ خطاب / طویل طنزیہ تقریر (Josheela khitab / Taqreer)',
   '["diatribe","tirade","lecture","exhortation"]',
   '["panegyric","accolade","whisper","tribute"]',
   'Instead of detailing the policy, the politician delivered a long harangue against the opposition.',
   'CSS Vocab', true),

  ('vocab-28', 'Iconoclast',
   'A person who attacks cherished beliefs or established institutions.',
   'بت شکن / باغیانہ سوچ والا (But-shikan / Baghiyana)',
   '["rebel","dissident","heretic","nonconformist"]',
   '["conformist","believer","traditionalist"]',
   'As an iconoclast, the author challenged traditional methods of civil service preparation in Pakistan.',
   'CSS Vocab', true),

  ('vocab-29', 'Implacable',
   'Unable to be appeased, pacified, or stopped.',
   'سخت گیر / سنگدل / جو راضی نہ ہو (Sakht-geer / Sangdil)',
   '["relentless","unyielding","inexorable","unappeasable"]',
   '["appeasable","merciful","yielding","forgiving"]',
   'The department showed implacable opposition to any extension of the recruitment age limit.',
   'FPSC Vocab', true),

  ('vocab-30', 'Incipient',
   'In an initial stage; beginning to happen or develop.',
   'ابتدائی / شروع ہونے والا (Ibtidai / Shuru-ati)',
   '["emerging","beginning","nascent","developing"]',
   '["mature","developed","full-blown","dying"]',
   'The medical team successfully arrested the incipient outbreak of dengue in the district.',
   'KPPSC Vocab', true),

  ('vocab-31', 'Intrepid',
   'Fearless and adventurous (often used for rhetorical effect).',
   'بے خوف / نڈر / دلیر (Be-khauf / Nadar / Daler)',
   '["fearless","brave","valiant","courageous"]',
   '["cowardly","fearful","timid","craven"]',
   'The intrepid rescue workers scaled the steep mountains of Swat to rescue trapped tourists.',
   'General Vocabulary', true),

  ('vocab-32', 'Laconic',
   'Using very few words of a person, speech, or style of writing.',
   'مختصر گو / کم سخن (Mukhtasar-go / Kam-sukhan)',
   '["brief","concise","terse","succinct"]',
   '["verbose","wordy","garrulous","loquacious"]',
   'His laconic replies in the mock interview were criticized for lacking explanation.',
   'CSS Vocab', true),

  ('vocab-33', 'Mendacious',
   'Not telling the truth; lying or deceitful.',
   'جھوٹا / غیر حقیقی (Jhoota / Ghayr-haqeeqi)',
   '["lying","untruthful","deceitful","dishonest"]',
   '["truthful","honest","sincere","veracious"]',
   'The court rejected the mendacious testimony provided by the fake witness.',
   'FPSC Vocab', true),

  ('vocab-34', 'Nefarious',
   'Wicked, villainous, or criminal (typically of an action or activity).',
   'شریر / بدکار / گھناؤنا (Sharir / Badkar / Ghinauna)',
   '["wicked","evil","villainous","heinous"]',
   '["noble","virtuous","righteous","good"]',
   'The Federal Investigation Agency exposed the nefarious scheme of transferring money through illegal channels.',
   'FPSC Vocab', true),

  ('vocab-35', 'Obdurate',
   'Stubbornly refusing to change one''s opinion or course of action.',
   'ضدی / ہٹ دھرم (Ziddi / Hatt-dharam)',
   '["stubborn","obstinate","intractable","inflexible"]',
   '["compliant","amenable","malleable","flexible"]',
   'Despite repeated warnings, the candidate remained obdurate and refused to hand over his mobile device.',
   'CSS Vocab', true),

  ('vocab-36', 'Pervasive',
   'Spreading widely throughout an area or a group of people.',
   'سرایت کرنے والا / ہمہ گیر (Sarayat-kunanda / Hama-geer)',
   '["widespread","omnipresent","prevalent","rife"]',
   '["localized","limited","rare","restricted"]',
   'The pervasive influence of digital media has reshaped competitive exam preparation in Pakistan.',
   'General Vocabulary', true),

  ('vocab-37', 'Sycophant',
   'A person who acts obsequiously toward someone important in order to gain advantage.',
   'چاپلوس / خوشامدی (Chaploos / Khushamdi)',
   '["flatterer","toady","lackey","fawner"]',
   '["rebel","independent","skeptic"]',
   'Instead of offering honest feedback, the sycophant kept praising the director''s failed policy.',
   'KPPSC Vocab', true),

  ('vocab-38', 'Ubiquitous',
   'Present, appearing, or found everywhere.',
   'ہر جگہ موجود / ہمہ گیر (Har-jah-maujood / Hama-geer)',
   '["omnipresent","widespread","universal","pervasive"]',
   '["rare","scarce","uncommon","absent"]',
   'Smartphones have become ubiquitous among competitive exam aspirants for video lectures.',
   'General Vocabulary', true)

ON CONFLICT (id) DO UPDATE SET
  word          = EXCLUDED.word,
  meaning       = EXCLUDED.meaning,
  urdu_meaning  = EXCLUDED.urdu_meaning,
  synonyms      = EXCLUDED.synonyms,
  antonyms      = EXCLUDED.antonyms,
  example       = EXCLUDED.example,
  category      = EXCLUDED.category,
  is_public     = EXCLUDED.is_public;
